language: ruby
cache: bundler
rvm:
  - 2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database "shoshin_test";' -U postgres
  - cp config/database.yml.travis config/database.yml
addons:
  postgresql: "9.5"
