sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
- 2.3.1
services:
- postgresql
before_script:
- psql -c 'create database "shoshin_test";' -U postgres
- cp config/database.yml.travis config/database.yml
addons:
  postgresql: '9.5'
notifications:
  webhooks:
    urls:
    - secure: aK5uBVYgx2jfGsAwN//SEvGHJgJrcE4cW87oDMA6nqFSllumV51xE56BADLng74gxFCXyVDan8LZ3KZDj2BV9vyXjXqvz8oAnVcmT0p4Vr46AWVgB0fZKc73H1QZ04r1BI2lq/mpMR+t/48ZBl65/vpjDpPBSxy5NiyBANsPxsG1xi8DCs57GdARkXDFGokmVrmEIb8SS5RRoPormqF80dtcqUpnSqQDI1dvw/ePCB0fgqDsNlZ67QnG+xoS7V03l7w7H3pT1p46ftApPNEI9N30i4T9nOUg6q1d/XgJaeYcGk/UyGERsoTc8Sdo/m61KtwtTKSL9P37NBxse4uAXuhgDsnPNPhFXxAcsSMiD7sR08kv+WQdypecDz4F0IwcNishVVnoUsqdvihJFSvh4Y3+Bm9T/awpoN/eeMUMkOLa2LlmlB1RJZVvt2JLTrDPVw1IhalWsPaVEycgSvZyqE5sbwW6BL7l51nQg+QHGeWlly5ZuubUbV8vip9uFYM6tNanFk+9aVev3uVj39d2OI/lTMsOVyijiRcUGJ7b+mbtx1+fKcfrkrghApxYMKuwBFnP2CXqW9jol+G4s8s1vnlq0EviKAkJ3SyiKuXgSRoY7JcvY3QB3WYmJ9QOkOcsKb0vHZ4vKBrZPZpS98678mEZQQpAig82kDaeo2pWK0Q=
    on_success: change
    on_failure: always
    on_start: never
