sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
- 2.3.1
services:
- postgresql
before_script:
- psql -c 'create database "shoshin_test";' -U postgres
- cp config/database.yml.travis config/database.yml
addons:
  postgresql: '9.5'
notifications:
  webhooks:
    urls:
      secure: rMdv6IFbleS5H4PXMR2QYKbgTZ9Pqd4FKxdKR0hPjYnOjAFwXm3nKzNTRkOBC2W8AGRcAKofEiUhWJ6Qvo3aUkMj0NXV9Meo8EK0XPAOXxnsm4MfetmptZ5s41xyUXb7Hmvb8EpqiyOxSGc0c73mFb3/if05+GCw7OKVRitLvLDdEyaKrLqYpohxcrovtRWIQV00/uJQALiZwZfe7tMfpLDFzOY8JIkFMqQs5qdzGf2/nJgFHTW8OajNWot4dJ4814RTkjN+fZTaXsXSbYw8AytGYNuz3xHupU3u+v1TtmglZp8KgcQlgf6zQXaXjwwR1yDRkHrlFMWyc/WZOfcIKYQ6pvH9OdvKKTP/XGrmGkQSsjir9JUrcNniV1e+xu8scdSWXwSSaKv5hcCIsVs6Ii66OqMP8Q4tnNOiAHrQDy9EKuMk4PgQUuI0uJjiiHvPsosvMBt9lcBHPYKkNVLTh37Y17Z1iiWBri8XZvmyTHC2On+SIMee5xBJUuCLVavIpogrnZWNHso/ltfqoYNxQ+Q05i+mtlI7Ex1MNbo7VPUI3e/6CxE8P51d/3E0h7UPArRT72s/nsMQoigsqoyfRr3uKBLX0Qz0mvMX8rxbwWc+X4np7CekxP0vZF1mnyYdzpOXiOqmi/IC0dA8D2h7qjSRabXlMQaE+mutBwzkHWc=
    on_success: change
    on_failure: always
    on_start: never
